version: '2'
services:
  logger:
    build:
      context: ./
      dockerfile: ./logger/Dockerfile
    container_name: slack-patron-logger
    volumes:
      - ./config.yml:/usr/local/slack-patron/config.yml
    links:
     - mongo

  viewer:
    build:
      context: ./
      dockerfile: ./viewer/Dockerfile
    container_name: slack-patron-viewer
    volumes:
      - ./config.yml:/usr/local/slack-patron/config.yml
    ports:
     - "9292:9292"
    links:
     - mongo

  mongo:
    image: mongo
