version: '3'
services:
  logger:
    build:
      context: ./
      dockerfile: ./logger/Dockerfile
    container_name: slack-patron-logger
    volumes:
      - .:/usr/local/slack-patron
    depends_on:
      - connector
    restart: always

  viewer:
    build:
      context: ./
      dockerfile: ./viewer/Dockerfile
    container_name: slack-patron-viewer
    volumes:
      - .:/usr/local/slack-patron
    depends_on:
      - connector
    ports:
      - "127.0.0.1:9292:9292"
    restart: always

  connector:
    build: connector
    depends_on:
      - mongo
      - elasticsearch
    restart: always

  elasticsearch:
    build: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always

  mongo:
    image: mongo:4.0-xenial
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - mongodata:/data/db
      - mongo-log:/var/log/mongodb
    restart: always

volumes:
  esdata:
  mongodata:
  mongo-log:
