version: '3'
services:
 logger:
   build:
     context: ./
     dockerfile: ./logger/Dockerfile
   container_name: slack-patron-logger

 viewer:
   build:
     context: ./
     dockerfile: ./viewer/Dockerfile
   container_name: slack-patron-viewer
   ports:
    - "9292:9292"

 elasticsearch:
  build:
    context: ./elasticsearch
  expose:
    - 9200
    - 9300

 elasticsearch-setup:
   build:
     context: ./elasticsearch-setup
   depends_on:
     - elasticsearch

 mongo:
   image: mongo:4.0-xenial
   entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
   expose:
     - 27017

 mongo2:
   image: mongo:4.0-xenial
   entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
   expose:
     - 27017

 mongo3:
   image: mongo:4.0-xenial
   entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
   expose:
     - 27017

 mongo-setup:
   image: mongo:4.0-xenial
   depends_on:
     - mongo
     - mongo2
     - mongo3
   volumes:
     - ./scripts:/scripts
   entrypoint: [ "/scripts/setup.sh" ]

 connector:
   build:
     context: ./connector/
   depends_on:
     - mongo-setup
     - elasticsearch-setup
