version: '2'
services:
  logger:
    build:
      context: ./
      dockerfile: ./logger/Dockerfile
    container_name: slack-patron-logger
    links:
     - mongo
    restart: always

  viewer:
    build:
      context: ./
      dockerfile: ./viewer/Dockerfile
    container_name: slack-patron-viewer
    ports:
     - "127.0.0.1:9292:9292"
    links:
     - mongo
    restart: always

  mongo:
    image: mongo
    command: --logpath=/var/log/mongodb/mongo.log --profile=1 --slowms=100
    volumes:
        - ./datadir:/data/db
        - ./mongo-log:/var/log/mongodb
    restart: always
