version: '3'
services:
  logger:
    build:
      context: ./
      dockerfile: ./logger/Dockerfile
    container_name: slack-patron-logger
    volumes:
      - .:/usr/local/slack-patron
    restart: always

  viewer:
    build:
      context: ./
      dockerfile: ./viewer/Dockerfile
    container_name: slack-patron-viewer
    volumes:
      - .:/usr/local/slack-patron
    ports:
      - "127.0.0.1:9292:9292"
    restart: always

  connector:
    build: connector
    environment:
      - MONSTACHE_DIRECT_READ_NS=slack_logger.messages
      - MONSTACHE_ES_URLS=http://elasticsearch:9200
      - MONSTACHE_MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
      - elasticsearch
    restart: always

  elasticsearch:
    build: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms640m -Xmx640m -XX:G1PeriodicGCInterval=60k
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always

  mongo:
    image: mongo:4.4.2
    command: --profile=1 --slowms=100 --bind_ip_all --replSet rs0
    volumes:
      - mongodata:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    restart: always

volumes:
  esdata:
  mongodata:
  oplog:
