version: '3'
services:
  logger:
    build:
      context: ./
      dockerfile: ./logger/Dockerfile
    container_name: slack-patron-logger
    links:
     - mongo
    restart: always

  viewer:
    build:
      context: ./
      dockerfile: ./viewer/Dockerfile
    container_name: slack-patron-viewer
    ports:
     - "127.0.0.1:9292:9292"
    links:
     - mongo
    restart: always
    depends_on:
      - connector

  elasticsearch:
   build:
     context: ./elasticsearch
   expose:
     - 9200
     - 9300

  elasticsearch-setup:
    build:
      context: ./elasticsearch-setup
    depends_on:
      - elasticsearch

  mongo:
    image: mongo:4.0-xenial
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
        - ./datadir:/data/db
        - ./mongo-log:/var/log/mongodb
    restart: always
    expose:
      - 27017

  mongo-setup:
    image: mongo:4.0-xenial
    depends_on:
      - mongo
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/scripts/setup.sh" ]

  connector:
    build:
      context: ./connector/
    depends_on:
      - mongo-setup
      - elasticsearch-setup