name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish viewer to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: tyage/slack-patron-viewer
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: viewer
    - name: Publish logger to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: tyage/slack-patron-logger
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: logger
