name: Publish Docker Hub
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish viewer to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: tyage/slack-patron-viewer
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: viewer
    - name: Publish logger to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: tyage/slack-patron-logger
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: logger
